name: toolbox
version: "0.0.3"
summary: set of usefull shell tools
description: |
 set of usefull shell tools

confinement: strict
grade: devel

apps:
    nano:
        command: nano
        plugs: [home]

    wget:
        command: wget
        plugs: [home, network]

    ag:
        command: ag
        plugs: [home]

    mc:
        command: mc
        plugs: [home, process-control, system-observe, mount-observe]

    mcdiff:
        command: mcdiff
        plugs: [home, process-control, system-observe, mount-observe]

    mcedit:
        command: mcedit
        plugs: [home, process-control, system-observe, mount-observe]

    mcview:
        command: mcview
        plugs: [home, process-control, system-observe, mount-observe]

    pastebinit:
        command: pastebinit
        plugs: [home, network]

    curl:
        command: curl
        plugs: [home, network]

    lsusb:
        command: lsusb
        plugs: [hardware-observe, network]

    usb-devices:
        command: usb-devices
        plugs: [hardware-observe, network]

    usbhid-dump:
        command: usbhid-dump
        plugs: [hardware-observe, network]

    update-usbids:
        command: update-usbids
        plugs: [hardware-observe, network]

    cppfilt:
        command: c++filt

    elfedit:
        command: elfedit

    readelf:
        command: readelf

    ld:
        command: ld

    ld-bfd:
        command: ld.bfd

    strings:
        command: strings

    size:
        command: size

    strip:
        command: strip

    objcopy:
        command: objcopy

    objdump:
        command: objdump

    addr2line:
        command: addr2line

    dwp:
        command: dwp

    as:
        command: as

    ar:
        command: ar

    gold:
        command: gold

    ld-gold:
        command: ld.gold

    nm:
        command: nm

    gprof:
        command: gprof

    ranlib:
        command: ranlib

    set-path:
        command: set-path
    screen:
        command: screen

parts:
    tools:
        source: .
        plugin: dump
        stage-packages: [wget, nano, silversearcher-ag, mc, pastebinit, curl, binutils, screen]
        filesets:
          fat:
            - -usr/lib/gcc
        stage:
            - $fat
        prime:
            - $fat
        organize:
            connect-interfaces: bin/connect-interfaces
            set-path: bin/set-path

    usbutils:
        source: https://github.com/gregkh/usbutils.git
        plugin: autotools
        build-packages:
            - libusb-1.0-0-dev
            - zlib1g
            - gawk
            - pkg-config
            - libudev-dev
        stage-packages: [libusb-1.0-0]
        configflags:
            - --prefix=/usr
            - --libdir=/usr/lib
            - --localstatedir=/var/snap/toolbox/common/
        prepare: |
            git submodule init
            git submodule update
            autoreconf --install --symlink
