name: toolbox
version: "0.0.3"
summary: set of usefull shell tools
description: |
 set of usefull shell tools

confinement: strict
grade: devel

apps:
    nano:
        command: nano
        plugs: [home]

    wget:
        command: wget
        plugs: [home, network]

    ag:
        command: ag
        plugs: [home]

    mc:
        command: mc
        plugs: [home, process-control, system-observe, mount-observe]

    mcdiff:
        command: mcdiff
        plugs: [home, process-control, system-observe, mount-observe]

    mcedit:
        command: mcedit
        plugs: [home, process-control, system-observe, mount-observe]

    mcview:
        command: mcview
        plugs: [home, process-control, system-observe, mount-observe]

    pastebinit:
        command: pastebinit
        plugs: [home, network]

    curl:
        command: curl
        plugs: [home, network]

    lsusb:
        command: lsusb

    usb-devices:
        command: usb-devices

    usbhid-dump:
        command: usbhid-dump

    update-usbids:
        command: update-usbids

    cppfilt:
        command: c++filt

    elfedit:
        command: elfedit

    readelf:
        command: readelf

    ld:
        command: ld

    ld-bfd:
        command: ld.bfd

    strings:
        command: strings

    size:
        command: size

    strip:
        command: strip

    objcopy:
        command: objcopy

    objdump:
        command: objdump

    addr2line:
        command: addr2line

    dwp:
        command: dwp

    as:
        command: as

    ar:
        command: ar

    gold:
        command: gold

    ld-gold:
        command: ld.gold

    nm:
        command: nm

    gprof:
        command: gprof

    ranlib:
        command: ranlib

    byobu:
        command: byobu

    set-path:
        command: set-path

    byobu-screen:
        command: byobu-screen
    ctail:
        command: ctail
    byobu-disable:
        command: byobu-disable
    byobu-ugraph:
        command: byobu-ugraph
    purge-old-kernels:
        command: purge-old-kernels
    byobu-select-session:
        command: byobu-select-session
    byobu-ulevel:
        command: byobu-ulevel
    byobu-quiet:
        command: byobu-quiet
    byobu-ctrl-a:
        command: byobu-ctrl-a
    byobu-export:
        command: byobu-export
    byobu-layout:
        command: byobu-layout
    vigpg:
        command: vigpg
    byobu-launcher-uninstall:
        command: byobu-launcher-uninstall
    byobu-select-backend:
        command: byobu-select-backend
    byobu:
        command: byobu
    byobu-janitor:
        command: byobu-janitor
    byobu-enable-prompt:
        command: byobu-enable-prompt
    byobu-keybindings:
        command: byobu-keybindings
    col1:
        command: col1
    byobu-launcher:
        command: byobu-launcher
    byobu-status:
        command: byobu-status
    byobu-launcher-install:
        command: byobu-launcher-install
    manifest:
        command: manifest
    byobu-prompt:
        command: byobu-prompt
    byobu-launch:
        command: byobu-launch
    byobu-enable:
        command: byobu-enable
    byobu-status-detail:
        command: byobu-status-detail
    byobu-disable-prompt:
        command: byobu-disable-prompt
    byobu-select-profile:
        command: byobu-select-profile
    byobu-config:
        command: byobu-config
    byobu-shell:
        command: byobu-shell
    byobu-reconnect-sockets:
        command: byobu-reconnect-sockets
    byobu-silent:
        command: byobu-silent
    wifi-status:
        command: wifi-status
parts:
    tools:
        source: .
        plugin: dump
        stage-packages: [wget, nano, silversearcher-ag, mc, pastebinit, curl, binutils, byobu, usbutils]
        filesets:
          fat:
            - -usr/lib/gcc
            - -usr/share
        stage:
            - $fat
        prime:
            - $fat
        organize:
            connect-interfaces: bin/connect-interfaces
            set-path: bin/set-path
